version: 1.0.{build}

branches:
  only:
    - development

skip_tags: true

init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "4.1.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - cd kbiwp/wp-content/themes/kasparabi/assets/
  - npm install
  - npm install -g grunt-cli
  - grunt compile_less

artifacts:
  - path: kasparabi.zip
    name: kasparabi
