version: 1.0.{build}

branches:
  only:
    - development

skip_tags: true

init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "4.1.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - cd kbiwp/wp-content/themes/kasparabi/assets/
  - npm install
  - npm install -g grunt-cli
  - grunt compile_less

deploy:
    # FTP deployment provider settings
  - provider: FTP
    protocol: ftps
    host: ftp.domeneshop.no
    username: petertflemno
    password:
      secure: 2T1/BoBV5UMpLZ886hM7PQ==
    folder: test
