version: 1.0.{build}

branches:
  only:
    - development

skip_tags: true

init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "4.1.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g grunt-cli
  - grunt compile_less
  - grunt build

build: off

artifacts:
  - path: \build
    name: kasparabi

deploy:
    # FTP deployment provider settings
  - provider: FTP
    protocol: ftp
    host: ftp.domeneshop.no
    username: petertflemno
    password:
      secure: 2T1/BoBV5UMpLZ886hM7PQ==
    folder: /release/1.0.{build}
    application: kasparabi
    skip_dirs: \\kbiwp\\wp-content\\plugins
